name: Clang Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest # or a specific version like '15'
        platform: x64

    - name: Configure CMake
      run: cmake -B build

    - name: Build with Clang
      run: cmake --build build